#Dockerfile

# Use a slim Python base image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /app

# Copy application files into container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port Flask app runs on
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]
